import { Inter } from 'next/font/google';
import '@styles/globals.css';
import Footer from '@shared/footer/Footer';
import Header from '@shared/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Bermejo Company',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='app'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
